apiVersion: v1
kind: Pod
metadata:
  name: model-inspect-pod
  namespace: pbl4
spec:
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
  containers:
    - name: model-store
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mypvc
          mountPath: "/pv/shared"
