import type { NextPage } from "next";
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from "../styles/Home.module.css";
import TopPage from "../components/top_page";
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Lorem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <TopPage />
      </main>
    </div>
  );
};

export default Home;
